### ISSUE TITLE
Larger Variety of Centrality Measures

### ISSUE THREAD

**Issue by BradKML** [barahona-research-group/MultiscaleCentrality#2]
There is a Centrality library called Centiserve which included a larger variety of centrality measures. Would be fun to see the correlation and accuracy of multiscale-ness of Centrality, as it seemed that Closeness and Degree Centrality is too cross-correlated.

From CentiServe in https://rdrr.io/cran/centiserve/man/:
- [ ] averagedis | Find the average distance of a node
- [ ] barycenter | Find the barycenter centrality score
- [ ] bottleneck | Find the BottleNeck centrality score
- [ ] centroid | Find the centroid value of graph vertices
- [ ] closeness.currentflow | Find current-flow closeness centrality
- [ ] closeness.freeman | Find the closeness centrality in a strongly connected graph
- [ ] closeness.latora | Find the variant (Latora) closeness centrality in a...
- [ ] closeness.residual | Find the residual closeness centrality
- [ ] closeness.vitality | Find the closeness vitality centrality in a strongly...
- [ ] clusterrank | Find the ClusterRank ranks in a graph
- [ ] communibet | Find the communicability betweenness centrality
- [ ] communitycent | Find the community-based node centrality
- [ ] crossclique | Find the cross-clique connectivity (centrality)
- [ ] decay | Find the decay centrality of a given vertex
- [ ] diffusion.degree | Find the variant (Latora) closeness centrality in a...
- [ ] dmnc | Find the density of maximum neighborhood component (DMNC) in...
- [ ] entropy | Find the entropy centrality in a graph
- [ ] epc | Find the edge percolated component (EPC) in a graph
- [ ] geokpath | Find the geodesic k-path centrality
- [ ] hubbell | Find the Hubbell centrality or the Hubbell Index
- [ ] katzcent | Find the Katz centrality (Katz Status Index)
- [ ] laplacian | Find the laplacian centrality
- [ ] leaderrank | Find the LeaderRank in a directed graph
- [ ] leverage | Find the leverage centrality
- [ ] lincent | Find the lin centrality in a graph
- [ ] lobby | Find the lobby index (centrality)
- [ ] markovcent | Find the markov centrality score
- [ ] mnc | Find the maximum neighborhood component (MNC)
- [ ] pairwisedis | Find the pairwise disconnectivity index
- [ ] radiality | Find the radiality centrality in a graph
- [ ] salsa | Find the SALSA as 'hub' or 'authority' score
- [ ] semilocal | Find the semi local centrality (or local centrality)
- [ ] topocoefficient | Find the topological coefficient of a node in a undirected...

According to NetRankr
- [ ] residual closeness (Dangalchev,2006)
- [ ] generalized closeness (Agneessens et al.,2017)
- [ ] decay centrality (Jackson, 2010)
- [ ] integration centrality (Valente & Foreman, 1998)
- [ ] subgraph centrality
- [ ] communicability centrality
- [ ] odd/even subgraph centrality
- [ ] katz status

**References**
- https://rdrr.io/cran/centiserve/
- https://www.rdocumentation.org/packages/tidygraph/versions/1.2.0/topics/centrality with reference to https://rdrr.io/cran/netrankr/man/netrankr.html
- http://cran.nexr.com/web/packages/CINNA/vignettes/CINNA.html#various-types-of-centralities-computation

With callbacks from https://github.com/GiulioRossetti/cdlib/issues/148 and https://github.com/igraph/igraph/issues/1741

**Comment by BradKML** [comment]
Cross-referencing https://github.com/networkx/networkx/discussions/4808

Oldham, Stuart, Ben Fulcher, Linden Parkes, Aurina Arnatkeviciute, Chao Suo, and Alex Fornito. 2019. “Consistency and Differences between Centrality Measures across Distinct Classes of Networks.” PLOS ONE 14 (7): e0220061. https://doi.org/10.1371/journal.pone.0220061.
![image](https://user-images.githubusercontent.com/58927531/118908311-c85e9d00-b953-11eb-96a8-fb866fdac090.png)
![image](https://user-images.githubusercontent.com/58927531/118908321-ce547e00-b953-11eb-9451-ffd683b3f657.png)

**Comment by arnaudon** [comment]
Thanks, I didn't know this repository and paper, feel free to do as you propose! This code is for a specific measure of centrality we designed in a research paper, so I'm not sure of the relevance of this issue in this particular repository.

**Comment by BradKML** [comment]
Idea: perhaps the Spearman correlation between multiscale centrality and these centrality measures will give more curious results?

**Comment by BradKML** [comment]
@arnaudon part of the problem comes from the image below from the paper, and it uses degree centrality and closeness centrality, which are somewhat correlated (compared to PageRank and Eigenvector centrality as replacement)
![](https://github.com/barahona-research-group/MultiscaleCentrality/blob/master/doc/figure_msc.png?raw=true)
